In [2]:
# 作业1: 土壤温度数据数组操作
import numpy as np

print("=" * 50)
print("作业1: 土壤温度数据数组操作")
print("=" * 50)

temp_data = np.array([
    [18.5, 22.3, 19.8],  
    [19.2, 23.1, 20.5],   
    [20.1, 24.5, 21.3],   
    [19.8, 23.8, 20.9],   
    [18.9, 22.7, 19.5],   
    [18.3, 21.9, 19.1],   
    [17.8, 21.5, 18.6]    
], dtype=np.float64)

print("\n(1) 创建7行3列的二维数组（dtype=float64）：")
print(temp_data)
print(f"数据类型: {temp_data.dtype}")

print("\n(2) 数组属性：")
print(f"  维度(ndim): {temp_data.ndim}")
print(f"  形状(shape): {temp_data.shape}")
print(f"  元素总数(size): {temp_data.size}")
print(f"  数据类型(dtype): {temp_data.dtype}")

print("\n(3) 周三（第3行）全天温度数据：")
wednesday = temp_data[2]  
print(wednesday)

print("\n(4) 每天中午（第2列）的温度数据：")
noon = temp_data[:, 1] 
print(noon)

print("\n(5) 周四到周六（第4-6行）早晚（第1和第3列）温度数据：")
result = temp_data[3:6, [0, 2]] 
print(result)

作业1: 土壤温度数据数组操作

(1) 创建7行3列的二维数组（dtype=float64）：
[[18.5 22.3 19.8]
 [19.2 23.1 20.5]
 [20.1 24.5 21.3]
 [19.8 23.8 20.9]
 [18.9 22.7 19.5]
 [18.3 21.9 19.1]
 [17.8 21.5 18.6]]
数据类型: float64

(2) 数组属性：
  维度(ndim): 2
  形状(shape): (7, 3)
  元素总数(size): 21
  数据类型(dtype): float64

(3) 周三（第3行）全天温度数据：
[20.1 24.5 21.3]

(4) 每天中午（第2列）的温度数据：
[22.3 23.1 24.5 23.8 22.7 21.9 21.5]

(5) 周四到周六（第4-6行）早晚（第1和第3列）温度数据：
[[19.8 20.9]
 [18.9 19.5]
 [18.3 19.1]]


In [8]:
# 作业2: 小麦种植密度与产量关系
import numpy as np

print("=" * 50)
print("作业2: 小麦种植密度与产量关系")
print("=" * 50)

density = np.arange(100, 420, 20) 
print("\n(1) 种植密度数组（株/m²）：")
print(density)
print(f"密度数组长度: {len(density)}")

np.random.seed(92) 
yield_data = 300 + 200 * np.random.rand(len(density))
print("\n(2) 模拟产量数据（千克/亩）：")
print(yield_data)

yield_per_plant = yield_data / density
print("\n(3) 平均单株产量（千克/亩 ÷ 株/m²）：")
for d, y, yp in zip(density, yield_data, yield_per_plant):
    print(f"  密度{d:3d}株/m²: 产量{y:.2f}千克/亩, 单株产量{yp:.4f}")

zero_array = np.zeros_like(density, dtype=np.float64)
zero_array = yield_per_plant 
print("\n(4) 全零数组存入单株产量后：")
print(zero_array)

作业2: 小麦种植密度与产量关系

(1) 种植密度数组（株/m²）：
[100 120 140 160 180 200 220 240 260 280 300 320 340 360 380 400]
密度数组长度: 16

(2) 模拟产量数据（千克/亩）：
[477.17609989 457.71631336 384.9456263  395.77392937 300.07081195
 471.27340921 370.66433867 397.34980914 388.25462126 487.71610899
 443.5357771  468.06983288 358.30367763 467.04708448 389.48741443
 357.85605096]

(3) 平均单株产量（千克/亩 ÷ 株/m²）：
  密度100株/m²: 产量477.18千克/亩, 单株产量4.7718
  密度120株/m²: 产量457.72千克/亩, 单株产量3.8143
  密度140株/m²: 产量384.95千克/亩, 单株产量2.7496
  密度160株/m²: 产量395.77千克/亩, 单株产量2.4736
  密度180株/m²: 产量300.07千克/亩, 单株产量1.6671
  密度200株/m²: 产量471.27千克/亩, 单株产量2.3564
  密度220株/m²: 产量370.66千克/亩, 单株产量1.6848
  密度240株/m²: 产量397.35千克/亩, 单株产量1.6556
  密度260株/m²: 产量388.25千克/亩, 单株产量1.4933
  密度280株/m²: 产量487.72千克/亩, 单株产量1.7418
  密度300株/m²: 产量443.54千克/亩, 单株产量1.4785
  密度320株/m²: 产量468.07千克/亩, 单株产量1.4627
  密度340株/m²: 产量358.30千克/亩, 单株产量1.0538
  密度360株/m²: 产量467.05千克/亩, 单株产量1.2974
  密度380株/m²: 产量389.49千克/亩, 单株产量1.0250
  密度400株/m²: 产量357.86千克/亩, 单株产量0.8946

(4) 全零数组存入单株产量后：
[4.

In [10]:
# 作业3: 农业气象三维数组操作
import numpy as np

print("=" * 50)
print("作业3: 农业气象三维数组操作")
print("=" * 50)

np.random.seed(123)
weather = np.zeros((4, 12, 2))
weather[:, :, 0] = 5 + 30 * np.random.rand(4, 12)   
weather[:, :, 1] = 200 * np.random.rand(4, 12)      

print("\n(1) 生成形状为(4,12,2)的三维数组weather：")
print(f"  数组形状: {weather.shape}")
print(f"  A地区1月数据（气温, 降水量）: {weather[0, 0]}")
print(f"  D地区12月数据（气温, 降水量）: {weather[3, 11]}")

weather_2d = weather.reshape(48, 2)
print("\n(2) reshape变形为(48,2)的二维数组：")
print(f"  变形后形状: {weather_2d.shape}")
print("  解释：每一行代表一个地区某个月份的数据，\n前12行是A地区1-12月，接下来12行是B地区1-12月，\n以此类推，共4个地区×12个月=48行，2列分别是气温和降水量")
print(f"  第1行（A地区1月）: {weather_2d[0]}")
print(f"  第13行（B地区1月）: {weather_2d[12]}")

weather_swapped = weather.swapaxes(1, 2)
print("\n(3) swapaxes交换维度后形状变为(4,2,12)：")
print(f"  新形状: {weather_swapped.shape}")

a_region_temp = weather_swapped[0, 0, :] 
print(f"  A地区全年气温数据（12个月）: {a_region_temp}")

weather_flat = weather.flatten()
print("\n(4) flatten展平为一维数组：")
print(f"  展平后形状: {weather_flat.shape}")
print(f"  元素总数: {weather_flat.size}")
print("  排列顺序：按最内层维度优先，即先遍历气象指标(2个)，\n再遍历月份(12个)，最后遍历地区(4个)。\n即：A-1月-气温, A-1月-降水, A-2月-气温, A-2月-降水, ...")
print(f"  前8个元素: {weather_flat[:8]}")

作业3: 农业气象三维数组操作

(1) 生成形状为(4,12,2)的三维数组weather：
  数组形状: (4, 12, 2)
  A地区1月数据（气温, 降水量）: [ 25.89407557 103.89702385]
  D地区12月数据（气温, 降水量）: [ 34.56679357 138.34035974]

(2) reshape变形为(48,2)的二维数组：
  变形后形状: (48, 2)
  解释：每一行代表一个地区某个月份的数据，
前12行是A地区1-12月，接下来12行是B地区1-12月，
以此类推，共4个地区×12个月=48行，2列分别是气温和降水量
  第1行（A地区1月）: [ 25.89407557 103.89702385]
  第13行（B地区1月）: [ 18.15716734 133.86275659]

(3) swapaxes交换维度后形状变为(4,2,12)：
  新形状: (4, 2, 12)
  A地区全年气温数据（12个月）: [25.89407557 13.58418005 11.80554361 21.53944307 26.58406909 17.6931938
 34.42292595 25.54489216 19.42795704 16.76352555 15.29534048 26.87149122]

(4) flatten展平为一维数组：
  展平后形状: (96,)
  元素总数: 96
  排列顺序：按最内层维度优先，即先遍历气象指标(2个)，
再遍历月份(12个)，最后遍历地区(4个)。
即：A-1月-气温, A-1月-降水, A-2月-气温, A-2月-降水, ...
  前8个元素: [ 25.89407557 103.89702385  13.58418005 122.57890515  11.80554361
  24.1257332   21.53944307 165.2681601 ]


In [11]:
# 作业4: 肥料试验数据分析
import numpy as np

print("=" * 50)
print("作业4: 肥料试验数据分析")
print("=" * 50)

N = np.array([0, 10, 20, 30, 40])          
yield_N = np.array([320, 385, 450, 478, 465])  
P = np.array([0, 5, 10, 15, 20])           
rate_P = np.array([0, 0.05, 0.12, 0.18, 0.15]) 

print("\n(1) 创建的数组：")
print(f"  氮肥用量 N: {N}")
print(f"  氮肥产量 yield_N: {yield_N}")
print(f"  磷肥用量 P: {P}")
print(f"  磷肥增产率 rate_P: {rate_P}")

mask = yield_N > 400
high_yield_N = N[mask]
high_yield_value = yield_N[mask]
print("\n(2) 产量超过400kg/亩的氮肥处理：")
print(f"  氮肥用量: {high_yield_N}")
print(f"  对应产量: {high_yield_value}")

marginal_yield = np.diff(yield_N)
print("\n(3) 每增加10kg氮肥的边际产量增量：")
for i, my in enumerate(marginal_yield):
    print(f"  从{N[i]}到{N[i+1]}kg/亩: {my:.1f}kg/亩")

print("\n(4) 磷肥增产率的数学变换：")
print(f"{'磷肥用量':<8} {'原始值':<10} {'平方根':<10} {'自然对数':<12} {'指数变换':<12}")
print("-" * 55)

rate_P_log = np.log(rate_P + 1e-10) 
rate_P_sqrt = np.sqrt(rate_P)
rate_P_exp = np.exp(rate_P)

for i in range(len(P)):
    p = P[i]
    orig = rate_P[i]
    sqrt_v = rate_P_sqrt[i]
    log_v = rate_P_log[i]
    exp_v = rate_P_exp[i]
    print(f"{p:<8} {orig:<10.4f} {sqrt_v:<10.4f} {log_v:<12.4f} {exp_v:<12.4f}")

print("\n观察：平方根变换后数据分布更均匀，更接近线性关系。")

作业4: 肥料试验数据分析

(1) 创建的数组：
  氮肥用量 N: [ 0 10 20 30 40]
  氮肥产量 yield_N: [320 385 450 478 465]
  磷肥用量 P: [ 0  5 10 15 20]
  磷肥增产率 rate_P: [0.   0.05 0.12 0.18 0.15]

(2) 产量超过400kg/亩的氮肥处理：
  氮肥用量: [20 30 40]
  对应产量: [450 478 465]

(3) 每增加10kg氮肥的边际产量增量：
  从0到10kg/亩: 65.0kg/亩
  从10到20kg/亩: 65.0kg/亩
  从20到30kg/亩: 28.0kg/亩
  从30到40kg/亩: -13.0kg/亩

(4) 磷肥增产率的数学变换：
磷肥用量     原始值        平方根        自然对数         指数变换        
-------------------------------------------------------
0        0.0000     0.0000     -23.0259     1.0000      
5        0.0500     0.2236     -2.9957      1.0513      
10       0.1200     0.3464     -2.1203      1.1275      
15       0.1800     0.4243     -1.7148      1.1972      
20       0.1500     0.3873     -1.8971      1.1618      

观察：平方根变换后数据分布更均匀，更接近线性关系。


In [12]:
# 作业5: 玉米生长模拟与施肥决策
import numpy as np

print("=" * 50)
print("作业5: 玉米生长模拟与施肥决策")
print("=" * 50)

np.random.seed(2024)

n_plants = 100
growth_days = 120

initial_height = np.random.normal(5, 1, n_plants)          
growth_rate = np.random.normal(1.5, 0.3, n_plants)          
random_fluctuation = np.random.uniform(-5, 5, n_plants)    

final_height = initial_height + growth_days * growth_rate + random_fluctuation

print("\n(1) 生成100株玉米模拟数据：")
print(f"  初始高度范围: {initial_height.min():.2f} ~ {initial_height.max():.2f} cm")
print(f"  日生长速率范围: {growth_rate.min():.2f} ~ {growth_rate.max():.2f} cm/天")
print(f"  随机波动范围: {random_fluctuation.min():.2f} ~ {random_fluctuation.max():.2f} cm")
print(f"  最终高度范围: {final_height.min():.2f} ~ {final_height.max():.2f} cm")

n_demand = np.round(final_height * 0.05 + 10, 1)
print("\n(2) 氮肥需求量（保留1位小数，g/株）：")
print(f"  前10株: {n_demand[:10]}")

short = final_height < 160
medium = (final_height >= 160) & (final_height <= 200)
tall = final_height > 200

short_count = np.sum(short)
medium_count = np.sum(medium)
tall_count = np.sum(tall)

short_avg = np.mean(final_height[short]) if short_count > 0 else 0
medium_avg = np.mean(final_height[medium]) if medium_count > 0 else 0
tall_avg = np.mean(final_height[tall]) if tall_count > 0 else 0

print("\n(3) 植株高度分级统计：")
print(f"  矮株 (<160cm): {short_count}株, 平均高度{short_avg:.2f}cm")
print(f"  中等 (160~200cm): {medium_count}株, 平均高度{medium_avg:.2f}cm")
print(f"  高株 (>200cm): {tall_count}株, 平均高度{tall_avg:.2f}cm")

avg_height = np.mean(final_height)
std_height = np.std(final_height)
median_height = np.median(final_height)
max_height = np.max(final_height)
min_height = np.min(final_height)

print("\n(4) 总体统计指标：")
print(f"  平均高度: {avg_height:.2f} cm")
print(f"  标准差: {std_height:.2f} cm")
print(f"  中位数: {median_height:.2f} cm")
print(f"  最大值: {max_height:.2f} cm")
print(f"  最小值: {min_height:.2f} cm")

above_avg = final_height > avg_height
fertilizer_plants = final_height[above_avg]
total_n_demand = np.sum(n_demand[above_avg])

print("\n(5) 高于平均高度的植株施肥：")
print(f"  高于平均高度的植株数: {np.sum(above_avg)}株")
print(f"  这些植株的总氮肥需求: {total_n_demand:.1f} g")
print(f"  平均每株施肥量: {total_n_demand/np.sum(above_avg):.1f} g/株")

作业5: 玉米生长模拟与施肥决策

(1) 生成100株玉米模拟数据：
  初始高度范围: 2.38 ~ 7.40 cm
  日生长速率范围: 0.72 ~ 2.31 cm/天
  随机波动范围: -5.00 ~ 4.69 cm
  最终高度范围: 86.71 ~ 282.87 cm

(2) 氮肥需求量（保留1位小数，g/株）：
  前10株: [19.5 19.5 20.7 20.2 16.6 21.2 17.6 16.  20.2 18.9]

(3) 植株高度分级统计：
  矮株 (<160cm): 21株, 平均高度135.54cm
  中等 (160~200cm): 42株, 平均高度180.40cm
  高株 (>200cm): 37株, 平均高度224.92cm

(4) 总体统计指标：
  平均高度: 187.45 cm
  标准差: 37.27 cm
  中位数: 188.04 cm
  最大值: 282.87 cm
  最小值: 86.71 cm

(5) 高于平均高度的植株施肥：
  高于平均高度的植株数: 51株
  这些植株的总氮肥需求: 1060.5 g
  平均每株施肥量: 20.8 g/株
